using System;
using System.Collections.Generic;
using System.Text;

namespace Cogent_RPG_Character_Sheet
{
    class CharacterData
    {
        public string CharacterName = "";
        public string PlayerName = "";
        public string Age = "";
        public string Race = "";
        public string Height = "";
        public string BodyType = "";
        public string Disposition = "";
        public string DisablingCharacteristics = "";
        public string History = "";
        public string BeliefsMorality = "";
        public string GoalsAspirations = "";
        public bool STR0 = false;
        public bool STR1 = false;
        public bool STR2 = false;
        public bool STR3 = false;
        public bool STR4 = false;
        public bool REF0 = false;
        public bool REF1 = false;
        public bool REF2 = false;
        public bool REF3 = false;
        public bool REF4 = false;
        public bool INT0 = false;
        public bool INT1 = false;
        public bool INT2 = false;
        public bool INT3 = false;
        public bool INT4 = false;
        public bool Perception0 = false;
        public bool Perception1 = false;
        public bool Perception2 = false;
        public bool Perception3 = false;
        public bool Perception4 = false;
        public bool Athletics0 = false;
        public bool Athletics1 = false;
        public bool Athletics2 = false;
        public bool Athletics3 = false;
        public bool Athletics4 = false;
        public bool Grapple0 = false;
        public bool Grapple1 = false;
        public bool Grapple2 = false;
        public bool Grapple3 = false;
        public bool Grapple4 = false;
        public bool Swim0 = false;
        public bool Swim1 = false;
        public bool Swim2 = false;
        public bool Swim3 = false;
        public bool Swim4 = false;
        public bool AimThrow0 = false;
        public bool AimThrow1 = false;
        public bool AimThrow2 = false;
        public bool AimThrow3 = false;
        public bool AimThrow4 = false;
        public bool Acrobatics0 = false;
        public bool Acrobatics1 = false;
        public bool Acrobatics2 = false;
        public bool Acrobatics3 = false;
        public bool Acrobatics4 = false;
        public bool RidePilot0 = false;
        public bool RidePilot1 = false;
        public bool RidePilot2 = false;
        public bool RidePilot3 = false;
        public bool RidePilot4 = false;
        public bool SleightOfHand0 = false;
        public bool SleightOfHand1 = false;
        public bool SleightOfHand2 = false;
        public bool SleightOfHand3 = false;
        public bool SleightOfHand4 = false;
        public bool Stealth0 = false;
        public bool Stealth1 = false;
        public bool Stealth2 = false;
        public bool Stealth3 = false;
        public bool Stealth4 = false;
        public bool Deception0 = false;
        public bool Deception1 = false;
        public bool Deception2 = false;
        public bool Deception3 = false;
        public bool Deception4 = false;
        public bool Persuasion0 = false;
        public bool Persuasion1 = false;
        public bool Persuasion2 = false;
        public bool Persuasion3 = false;
        public bool Persuasion4 = false;
        public bool Infiltration0 = false;
        public bool Infiltration1 = false;
        public bool Infiltration2 = false;
        public bool Infiltration3 = false;
        public bool Infiltration4 = false;
        public bool Survival0 = false;
        public bool Survival1 = false;
        public bool Survival2 = false;
        public bool Survival3 = false;
        public bool Survival4 = false;
        public bool Vocation1_1 = false;
        public bool Vocation1_2 = false;
        public bool Vocation1_3 = false;
        public bool Vocation1_4 = false;
        public bool Vocation2_1 = false;
        public bool Vocation2_2 = false;
        public bool Vocation2_3 = false;
        public bool Vocation2_4 = false;
        public bool Vocation3_1 = false;
        public bool Vocation3_2 = false;
        public bool Vocation3_3 = false;
        public bool Vocation3_4 = false;
        public string VocationLabel1 = "";
        public string VocationLabel2 = "";
        public string VocationLabel3 = "";
        public bool Proficiency1_1 = false;
        public bool Proficiency1_2 = false;
        public bool Proficiency2_1 = false;
        public bool Proficiency2_2 = false;
        public bool Proficiency3_1 = false;
        public bool Proficiency3_2 = false;
        public string ProficiencyLabel1 = "";
        public string ProficiencyLabel2 = "";
        public string ProficiencyLabel3 = "";
        public string Equipment = "";
        public string Inventory = "";
        public string Notes = "";
        public bool DestinyPoints1 = false;
        public bool DestinyPoints2 = false;
        public bool DestinyPoints3 = false;
        public bool DestinyPoints4 = false;
        public bool DestinyPoints5 = false;
        public bool DestinyPoints6 = false;
        public bool DestinyPoints7 = false;
        public bool DestinyPoints8 = false;
        public bool CommercePoints1 = false;
        public bool CommercePoints2 = false;
        public bool CommercePoints3 = false;
        public bool CommercePoints4 = false;
        public bool CommercePoints5 = false;
        public bool CommercePoints6 = false;
        public bool CommercePoints7 = false;
        public bool CommercePoints8 = false;
        public string Injury1 = "";
        public string Injury2 = "";
        public string Injury3 = "";
        public string Injury4 = "";
        public string Penalty1 = "";
        public string Penalty2 = "";
        public string Penalty3 = "";
        public string Penalty4 = "";

        public CharacterData()
        {
            
        }
    }
}
